auxiliaries/pipeline_auxiliaries.py: Fix call to time()
When the output directory already exists for a previous phase that
has not completed, the pipeline dies with this error when creating
a new, time-stamped command path:

  File "./auxiliaries/pipeline_auxiliaries.py", line 180, in
submit_pipeline_step_to_cluster
    cmds_path = os.path.join(tmp_dir, f'{job_name}_{time()}.cmds')
TypeError: 'module' object is not callable

We need to call time.time() instead of time().